### ISSUE TITLE
How to create an account in the head

### ISSUE THREAD

**Issue by NoRRt** [polevpn/polevpn_server#1]
Hello, how can I create an account and connect to the server through the client? A partial server for creating an account so that I can connect to the server through the client. does not have . or how

**Comment by polevpn** [comment]
create  a file named "users.credentials" then put username,password list in this file
the users.credentials format like  following:

user1,password1
user2,password2
user3,password3
.......

then in the server config.json,the auth.file.path configuration should be the "users.credentials". then on the client use these  to connect to server
{
    "endpoint":{
        "listen":"0.0.0.0:443",
        "cert_file":"./keys/server.crt",
        "key_file":"./keys/server.key"
    },
    "network_cidr":"10.8.0.0/16",
    "dns_server":"8.8.8.8",
    "client_route":["1.0.0.0/8", "2.0.0.0/7", "4.0.0.0/6", "8.0.0.0/5", "16.0.0.0/4", "32.0.0.0/3", "64.0.0.0/2", "128.0.0.0/1"],
    "server_route":[],
    "bind_ip":[],
    "upstream_traffic_limit":52428800,
    "downstream_traffic_limit":104857600,
    "auth":{
        "file":{
            "path":"users.credentials"
        }
    }
}
